-- generated by theme.sh — palette: emerald
-- window border colors (mirrors sway colors.conf)
hl.config({
    general = {
        col = {
            active_border   = "rgba(78cfa080)",
            inactive_border = "rgba(223f304d)",
        },
    },
})
