-- User overrides on top of Hyprland's own bare default config
-- (/usr/share/hypr/hyprland.lua, owned by the hyprland package itself —
-- Noctalia fully stripped, see ~/.config/hypr.noctalia-bak for the old setup)
dofile("/usr/share/hypr/hyprland.lua")

-- ── armojidots-hypr ──────────────────────────────────
-- Full port of armojidots (SwayFX). Shared variables, then one section per
-- sway module this mirrors (see comments). This file (plus colors.lua,
-- regenerated in place by theme.sh) is the only file edited for
-- monitor/input/appearance/keybind/window-rule/autostart config.

local mod = "SUPER"
local term = "kitty"
local files = "nemo"
local browser = "zen-browser"

------------------
---- MONITORS ----
------------------
-- HDMI-A-2: side monitor, portrait, on the left
hl.monitor({ output = "HDMI-A-2", mode = "preferred", position = "0x0", scale = 1, transform = 1 })

-- DP-2: main monitor, 240Hz. HDR/color management (cm/bitdepth/
-- sdrbrightness/sdrsaturation) lives in monitor-dp2.lua, owned + rewritten
-- by the armoji-hdr GTK4 panel (/set > HDR) — same dofile pattern as
-- colors.lua. If you change DP-2's mode/position/scale here, also update
-- the GEOMETRY constant in armoji-hdr, since it rewrites the whole rule.
dofile(os.getenv("HOME") .. "/.config/hypr/monitor-dp2.lua")

-- DP-1: control-room TV (Samsung 1366x768@60), to the right of DP-2. No
-- waybar here on purpose (waybar/config.jsonc only has bar entries for
-- DP-2/HDMI-A-2) — this output is a dedicated always-on dashboard, not a
-- normal desktop. See the AUTOSTART section for what populates it.
hl.monitor({ output = "DP-1", mode = "1366x768@60", position = "3640x0", scale = 1 })

-- generated by theme.sh — window border colors (mirrors sway colors.conf)
dofile(os.getenv("HOME") .. "/.config/hypr/colors.lua")

--------------------
---- INPUT ---------
--------------------
-- mirrors sway input.conf: mouse (global input.*) vs touchpad (input.touchpad.*)
hl.config({
    input = {
        -- mouse: classic wheel, no acceleration curve (flat), slightly slowed
        natural_scroll = false,
        accel_profile  = "flat",
        sensitivity    = -0.4,

        -- keyboard layout: EN/LT, Shift+Alt chord toggles
        kb_layout  = "us,lt",
        kb_options = "grp:alt_shift_toggle",

        touchpad = {
            -- Windows-style scrolling (down motion scrolls up)
            natural_scroll        = true,
            disable_while_typing  = false,
        },
    },

    -- Both default to false. Without this, Hyprland's own native DPMS-wake
    -- only responds to some input (clicks) and not plain mouse movement —
    -- confirmed live: after DP-2's [[oled-idle-off]] blank, moving the
    -- mouse alone didn't wake it (or was noticeably slow, presumably
    -- waiting on hypridle's on-resume script instead of an immediate
    -- native wake), while clicking did. hypridle's on-resume listener
    -- still exists as a backstop for anything these miss.
    misc = {
        mouse_move_enables_dpms = true,
        key_press_enables_dpms  = true,
    },
})

-- Cursor theme (Bibata-Modern-Classic) — environment-d/cursor.conf covers
-- XWayland/portal apps via XCURSOR_THEME; these cover native Hyprland use
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")

-- QT apps (qt5ct/qt6ct, colors generated by theme.sh). QT_QPA_PLATFORMTHEME
-- accepts a fallback list — only qt6ct is installed right now, qt5ct is
-- listed too so it starts working the moment it's installed, no edit needed
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct;qt6ct")

--------------------------------
---- APPEARANCE / EFFECTS ------
--------------------------------
-- mirrors sway appearance.conf + effects.conf.
hl.config({
    general = {
        gaps_in     = 10,
        gaps_out    = 12,   -- matches sidebar-control.sh's GAP (screen-edge inset)
        border_size = 1,   -- paper-thin; opacity carries the focus hint, not a fat border
    },

    decoration = {
        rounding       = 10,

        -- focused window stays fully opaque; everything else fades back a
        -- touch so focus reads from transparency, not from a heavy border
        active_opacity   = 1.0,
        inactive_opacity = 0.85,

        dim_inactive = true,
        dim_strength = 0.08,

        shadow = {
            enabled       = true,
            range         = 18,
            color         = "0x70000000", -- #00000070
            color_inactive = "0x40000000", -- #00000040
        },

        blur = {
            enabled = true,
            size    = 4,
            passes  = 2,
        },
    },
})

-- Layer-shell blur (waybar, the custom GTK4 daemons' glass pills). This
-- USED TO be unnecessary — global decoration.blur.enabled alone was
-- confirmed live to reach layer surfaces too, no per-layer rule needed —
-- but that stopped being true at some point (likely a Hyprland update
-- changing layer-blur inheritance) and none of these had blur any more.
-- HL.LayerRuleSpec has its own explicit `blur` field now; every glass
-- surface needs an opt-in rule.
-- ignore_alpha is required too, not optional: without it blur covers the
-- layer's whole RECTANGULAR bounds regardless of the pill's own rounding —
-- confirmed live as "one big line of blur" with square corners on waybar,
-- spotlight, and the OSD. ignore_alpha skips blurring pixels at/below that
-- opacity, which is everywhere outside the actual rounded pill shape GTK
-- draws (the rest of the surface is fully transparent), so blur ends up
-- naturally clipped to the pill.
hl.layer_rule({ name = "waybar-blur", match = { namespace = "waybar" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "armoji-osd-blur", match = { namespace = "armoji-osd" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "armoji-dock-blur", match = { namespace = "armoji-dock" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "spotlight-search-blur", match = { namespace = "spotlight-search" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "spotlight-list-blur", match = { namespace = "spotlight-list" }, blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "swaync-blur", match = { namespace = "swaync-control-center" }, blur = true, ignore_alpha = 0.5 })

----------------------
---- WINDOW RULES ----
----------------------
-- Floating glass terminals for TUI tools (nmtui, pulsemixer, …). Blur comes
-- from the default config's already-enabled global blur — no per-layer
-- override needed, just normal Hyprland blur.
hl.window_rule({ name = "float-tui", match = { class = "float-tui" }, float = true, size = "900 620", center = true })

-- Zen Browser's pop-out Picture-in-Picture video: float it and pin it
-- (Hyprland's "pin" = sway's "sticky", visible across every workspace)
hl.window_rule({
    name  = "zen-pip",
    match = { class = "^(zen)$", title = "^Picture-in-Picture$" },
    float = true,
    pin   = true,
})

-- GTK apps join the glass: slight transparency (SwayFX blur behind them ->
-- Hyprland's already-global blur)
hl.window_rule({ name = "nemo-opacity", match = { class = "^(nemo)$" }, opacity = "0.93" })
hl.window_rule({ name = "pavucontrol-opacity", match = { class = "^(org.pulseaudio.pavucontrol)$" }, opacity = "0.93" })

-- Monitor config (nwg-displays, confirmed to support Hyprland natively):
-- float + center instead of tiling in
hl.window_rule({
    name  = "nwg-displays",
    match = { class = "^(nwg-displays)$" },
    float = true,
    size  = "900 650",
    center = true,
})

-- HDR/display-tuning panel (armoji-hdr), /set > HDR
hl.window_rule({
    name  = "armoji-hdr",
    match = { class = "^(org.armojidots.HDR)$" },
    float = true,
    center = true,
})

-- Sidebar terminals: floated + pinned (sway's "sticky enable" — visible on
-- every workspace), geometry owned by hypr-scripts/sidebar-control.sh.
-- Show/hide is done by moving on/off-screen (sidebar.sh), NOT Hyprland
-- special workspaces — that seemed right at first but broke badly: while a
-- special workspace is the active one on a monitor it silently absorbs any
-- new window opened, and blocks focus from reaching regular windows.
hl.window_rule({ name = "sidebar-term", match = { class = "sidebar-term" }, float = true, pin = true })
hl.window_rule({ name = "sidebar-claude", match = { class = "sidebar-claude" }, float = true, pin = true })

-- Viber's separate "new message" toast window is auto-killed on open (its
-- main window is untouched) — see hypr-scripts/activation-watch.sh, since
-- Hyprland's windowrule engine has no declarative "close on match" action
-- (unlike sway's for_window ... kill).

---------------------------------
---- KEYBINDS: APPS/WINDOWS -----
---------------------------------
-- hl.bind() is additive, not overriding — a base default on the same combo
-- keeps firing ALONGSIDE a new bind unless explicitly cleared first (verified
-- live: SUPER+Q fired both "exec terminal" and "close window" until unbound).
-- Clear every base default this section redefines before rebinding it.
for _, combo in ipairs({
    "SUPER + Q", "SUPER + E", "SUPER + R",
    "SUPER + Left", "SUPER + Right", "SUPER + Up", "SUPER + Down",
    "SUPER + SHIFT + S",
    "XF86AudioRaiseVolume", "XF86AudioLowerVolume", "XF86AudioMute", "XF86AudioMicMute",
    "XF86MonBrightnessUp", "XF86MonBrightnessDown",
    "XF86AudioPlay", "XF86AudioPause", "XF86AudioNext", "XF86AudioPrev",
}) do
    hl.unbind(combo)
end

hl.bind(mod .. " + T", hl.dsp.exec_cmd(term))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(files))
hl.bind(mod .. " + W", hl.dsp.exec_cmd(browser))

-- Spotlight (custom launcher — armoji-spotlight)
hl.bind(mod .. " + D", hl.dsp.exec_cmd("~/.local/bin/armoji-spotlight"))

-- Window controls
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + F", hl.dsp.window.fullscreen())

-- Lock screen
hl.bind(mod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Notification center
hl.bind(mod .. " + N", hl.dsp.exec_cmd("swaync-client -t"))

-- Quick-access sidebar terminals (toggle shows/hides, never kills)
hl.bind(mod .. " + R", hl.dsp.exec_cmd("~/.local/bin/sidebar.sh term"))
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.local/bin/sidebar.sh claude"))

-- Sidebar dock edge + size (acts on whichever sidebar was shown/toggled most
-- recently) — see hypr-scripts/sidebar-control.sh
hl.bind(mod .. " + SHIFT + H", hl.dsp.exec_cmd("~/.local/bin/sidebar-control.sh toggle-sides"))
hl.bind(mod .. " + SHIFT + M", hl.dsp.exec_cmd("~/.local/bin/sidebar-control.sh toggle-mode"))
hl.bind(mod .. " + SHIFT + V", hl.dsp.exec_cmd("~/.local/bin/sidebar-control.sh toggle-size"))

-- General window move/resize (overrides the base config's focus-by-arrow
-- binds — armojidots uses arrows for move/resize, not focus)
hl.bind(mod .. " + Left",  hl.dsp.window.move({ direction = "l" }))
hl.bind(mod .. " + Right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mod .. " + Up",    hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + Down",  hl.dsp.window.move({ direction = "d" }))

local function resize_by(dx, dy)
    local w = hl.get_active_window()
    if not w then return end
    hl.dispatch(hl.dsp.window.resize({ x = w.size.x + dx, y = w.size.y + dy }))
end
hl.bind(mod .. " + SHIFT + Left",  function() resize_by(-20, 0) end)
hl.bind(mod .. " + SHIFT + Right", function() resize_by(20, 0) end)
hl.bind(mod .. " + SHIFT + Up",    function() resize_by(0, -20) end)
hl.bind(mod .. " + SHIFT + Down",  function() resize_by(0, 20) end)

-- Screenshot: select a region → clipboard + notification with thumbnail
hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd(
    "sh -c 'f=/tmp/armoji-screenshot.png; grim -g \"$(slurp)\" \"$f\" && wl-copy --type image/png < \"$f\" && notify-send -t 3000 -h \"string:image-path:file://$f\" \"\xF3\xB0\xB9\x91 Screenshot\" \"Region copied to clipboard\"'"
))

-- Hold Win + left-drag to move windows, Win + right-drag to resize —
-- already native in the base config (mod+mouse:272/273), no override needed

--------------------------
---- MEDIA / FN KEYS -----
--------------------------
-- Volume/brightness routed through osd.sh so the armoji-osd pill pops up
-- (Windows-11-style), works over fullscreen apps too. --locked equivalent
-- is the `locked = true` bind option (keeps working on the lock screen).
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.local/bin/osd.sh volume-up"),   { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.local/bin/osd.sh volume-down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("~/.local/bin/osd.sh mute-toggle"), { locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("~/.local/bin/osd.sh brightness-up"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.local/bin/osd.sh brightness-down"), { locked = true, repeating = true })

hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
hl.bind("XF86AudioStop",  hl.dsp.exec_cmd("playerctl stop"),       { locked = true })

------------------------------------------------
---- PER-MONITOR WORKSPACES (swaysome-alike) ----
------------------------------------------------
-- Hyprland has no native "workspace N per monitor" selector (verified live:
-- the "m~N" syntax used in Noctalia's leftover config does NOT actually
-- switch workspaces on this Hyprland version — only "m+1"/"m-1" relative
-- stepping works). Reimplemented by hand instead, replicating swaysome's own
-- numbering exactly: group digit (1 = DP-2 main monitor, 2 = HDMI-A-2 side)
-- concatenated with the pressed digit — "11".."19","110" / "21".."29","210".
local MONITOR_GROUP = { ["DP-2"] = 1, ["HDMI-A-2"] = 2, ["DP-1"] = 3 }

-- clear the base config's global-workspace binds on the same keys (see the
-- additive-binds note above the KEYBINDS section)
for i = 1, 10 do
    local key = i % 10
    hl.unbind(mod .. " + " .. key)
    hl.unbind(mod .. " + SHIFT + " .. key)
end

local function group_ws(n)
    local mon = hl.get_active_monitor()
    local g = (mon and MONITOR_GROUP[mon.name]) or 1
    return tonumber(tostring(g) .. tostring(n))
end

for i = 1, 10 do
    local key = i % 10
    -- Switch to workspace N on the focused monitor only
    hl.bind(mod .. " + " .. key, function()
        hl.dispatch(hl.dsp.focus({ workspace = group_ws(i) }))
    end)
    -- Move focused window to workspace N on its monitor, and follow
    hl.bind(mod .. " + SHIFT + " .. key, function()
        local t = group_ws(i)
        hl.dispatch(hl.dsp.window.move({ workspace = t }))
        hl.dispatch(hl.dsp.focus({ workspace = t }))
    end)
    -- Move EVERYTHING on the current workspace to workspace N (same
    -- monitor), and follow — move-workspace.sh equivalent
    hl.bind(mod .. " + ALT + " .. key, function()
        local cur = hl.get_active_workspace()
        if not cur then return end
        local t = group_ws(i)
        for _, w in ipairs(hl.get_workspace_windows(cur.id)) do
            hl.dispatch(hl.dsp.window.move({ window = "address:" .. w.address, workspace = t }))
        end
        hl.dispatch(hl.dsp.focus({ workspace = t }))
    end)
end

-------------------
---- AUTOSTART ----
-------------------
-- Initialize per-monitor workspace groups (swaysome's `exec swaysome
-- init 1` equivalent). Without this, anything that opens before the
-- first Win+N press lands on Hyprland's own default plain-numbered
-- workspace (1, 2, …) instead of the group-prefixed one (11.., 21..) and
-- becomes unreachable through any of the binds above — confirmed live: a
-- session-start window got stranded on plain workspace "1", invisible to
-- every Win+1..0 press ("workspaces are broken").
--
-- Run at both hyprland.start AND on every monitor.added: a cold boot's
-- physical displays can still be mode-negotiating when hyprland.start
-- fires, so hl.get_monitors() there can come back empty/incomplete and
-- silently no-op for whichever monitor wasn't ready yet — this only ever
-- showed up on a real cold boot, never during a `hyprctl reload` (monitors
-- already active by then), which is why it went unnoticed in testing.
-- Idempotent either way (re-focusing an already-correct group is harmless),
-- so no de-dup needed between the two triggers.
local function init_workspace_groups()
  for _, m in ipairs(hl.get_monitors()) do
    local g = MONITOR_GROUP[m.name]
    if g then
      hl.dispatch(hl.dsp.focus({ monitor = m.name }))
      hl.dispatch(hl.dsp.focus({ workspace = g * 10 + 1 }))
    end
  end
end
-- Control-room TV (DP-1): populate its dedicated workspace (31) with
-- htop/cava/Jellyfin/voice-control panes. Guarded on DP-1 actually being
-- connected (same monitor-not-ready-at-cold-boot concern as
-- init_workspace_groups above) — control-room-launch.sh itself is also
-- idempotent, so firing this from both triggers below is harmless.
local function launch_control_room()
  for _, m in ipairs(hl.get_monitors()) do
    if m.name == "DP-1" then
      -- TTS null-sink + loopback (control-room-voice.py's speech, and the
      -- only thing control-room-cava.sh's dedicated cava instance reacts
      -- to) must exist before the panes that depend on it start.
      hl.exec_cmd("~/.local/bin/control-room-audio-setup.sh")
      hl.exec_cmd("~/.local/bin/control-room-launch.sh")
      return
    end
  end
end

hl.on("monitor.added", init_workspace_groups)
hl.on("monitor.added", launch_control_room)

hl.on("hyprland.start", function ()
  init_workspace_groups()

  -- Hand the session environment to systemd user services (they need
  -- WAYLAND_DISPLAY to show GUI), then (re)start them with it — mirrors
  -- sway's autostart.conf. Restarting here guarantees they come up with the
  -- session environment; all four units are also WantedBy=graphical-session
  -- .target and Restart=on-failure.
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE; dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP; systemctl --user restart elephant walker armoji-spotlight armoji-dock armoji-osd")

  hl.exec_cmd("~/.local/bin/theme.sh startup")
  hl.exec_cmd("swaync")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("~/.local/bin/bluelight-watch.sh")
  hl.exec_cmd("~/.config/waybar/scripts/bluelight.sh startup")
  -- case RGB off 21:00-05:00 (theme.sh apply_rgb/rgb-recheck)
  hl.exec_cmd("~/.local/bin/rgb-watch.sh")
  -- Caps Lock / Num Lock toggle notifications
  hl.exec_cmd("~/.local/bin/lock-watch.sh")
  -- Jump-to-window-on-urgent, with per-app exceptions (Viber toast auto-kill)
  hl.exec_cmd("~/.local/bin/activation-watch.sh")
  -- Low battery notifications (20/10/5%) — self-guards out on a desktop
  -- with no battery
  hl.exec_cmd("~/.local/bin/battery-watch.sh")
  hl.exec_cmd("waybar")

  launch_control_room()
end)
