-- generated by armoji-hdr — DP-2 monitor rule (geometry + HDR/color management)
hl.monitor({
  output = "DP-2",
  mode = "2560x1440@240",
  position = "1080x0",
  scale = 1,
  cm = "srgb",
  bitdepth = 10,
  sdr_eotf = "srgb",
  sdrbrightness = 2.00,
  sdrsaturation = 1.00,
  max_luminance = 1000,
  max_avg_luminance = 449,
})
