preload = ~/dotfiles/wallpapers/current

wallpaper {
  monitor = DP-2
  path = ~/dotfiles/wallpapers/current
}

wallpaper {
  monitor = HDMI-A-2
  path = ~/dotfiles/wallpapers/current
}

splash = false
